config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get :health, to: ->( _env ) { [ 200, {}, [ "ok" ] ] }

  get "/login", as: :login_form, to: "auth#login_form"
  post "/login", as: :login, to: "auth#login"
  delete "/login", as: :remove_login, to: "auth#logout"
  get "/logout", as: :logout, to: "auth#logout"
  post "/token/:id", as: :token, to: "auth#token"

  scope :x do
    resources :patrons, param: :name, only: [ :show ] do
      post :add_role, as: :add_role, to: "patrons#add_role"
    end
    resources :roles, param: :name, except: [ :destroy ]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_auth.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: email_auths
#
#  id                       :bigint           not null, primary key
#  email                    :string(255)
#  last_logged_in_at        :datetime
#  password_digest          :string(255)
#  recovery_password_digest :string(255)
#  patron_id                :bigint           not null
#
# Indexes
#
#  index_email_auths_on_email      (email) UNIQUE
#  index_email_auths_on_patron_id  (patron_id)
#
# Foreign Keys
#
#  fk_rails_...  (patron_id => patrons.id)
#
class EmailAuth < ApplicationRecord
  before_validation :downcase_email

  belongs_to :patron, optional: false
  has_secure_password
  has_secure_password :recovery_password, validations: false

  validates :email,
            uniqueness: { case_sensitive: false },
            length: { maximum: 255 },
            allow_nil: true,
            format: { with: /\A[a-zA-Z0-9_\-@.]+\z/ }

  def roles
    patron.roles.map( &:name )
  end

  private

  def downcase_email
    self.email = email&.downcase
  end
end

app/models/patron.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: patrons
#
#  id          :bigint           not null, primary key
#  auth_type   :enum             default("none"), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  external_id :string(255)      not null
#
# Indexes
#
#  index_patrons_on_external_id  (external_id) UNIQUE
#
class Patron < ApplicationRecord
  rolify

  enum auth_type: {
    external: "none",
    email: "email",
    oauth2: "oauth2",
  }

  has_one :email_auth, dependent: :destroy

  validates :external_id, presence: true, uniqueness: true, length: { maximum: 255 }
end

app/models/role.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: roles
#
#  id            :bigint           not null, primary key
#  name          :string
#  resource_type :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  resource_id   :bigint
#
# Indexes
#
#  index_roles_on_name      (name)
#  index_roles_on_resource  (resource_type,resource_id)
#
class Role < ApplicationRecord
  scopify
  has_and_belongs_to_many :patrons, join_table: :patrons_roles
  belongs_to :resource, polymorphic: true, optional: true

  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authorizations

  def unauthorized
    return head( :unauthorized ) if ENV[ "HARD_UNAUTH" ] == "true"

    redirect_to login_form_path( continue: request.path )
  end
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :logout, :token ]
  before_action :normazlie_continue

  before_action :verify_login_params, only: [ :login ]
  before_action :validate_user, only: [ :login ]

  before_action :validate_auth, only: [ :token ]
  before_action :load_patron, only: [ :token ]

  def login_form
    redirect_to params[ :continue ] if authorizations_in_cookie?
  end

  def login
    @user.update! last_logged_in_at: Time.now.utc
    auth_cookie Token.new( id: request.request_id, roles: @user.roles )
    redirect_to params[ :continue ]
  end

  def logout
    cookies[ cookie_name ] = nil
    redirect_to params[ :continue ]
  end

  def token
    auth_cookie Token.new( id: request.request_id, roles: @patron.roles.map( &:name ) )
    redirect_to params[ :continue ]
  end

  private

  def normazlie_continue
    params[ :continue ] ||= "/"
  end

  def verify_login_params
    return nil if params.key?( :username ) && params.key?( :password )

    flash[ :error ] = "Request is invlaid, parameters are missing"
    render status: :bad_request, template: "auth/login_form"
  end

  def validate_user
    @user = EmailAuth.find_by email: params[ :username ]
    return nil if @user&.patron&.email? && @user.authenticate( params[ :password ] )

    flash[ :error ] = "Invalid credentials"
    render status: :unauthorized, template: "auth/login_form"
  end

  def validate_auth
    return nil if params[ :token ] == ENV[ "SECURITY_TOKEN" ]

    head :unauthorized
  end

  def load_patron
    @patron = Patron.find_by external_id: params[ :id ]
    return nil if @patron&.external?

    head :not_found
  end

  def auth_cookie( token )
    cookies[ cookie_name ] = {
      value: token.to_s,
      expires: 1.hour,
      same_site: :Strict,
    }
  end
end

app/controllers/concerns/authorizations.rb
# frozen_string_literal: true

module Authorizations
  protected

  def cookie_name
    ENV.fetch( "AUTH_COOKIE_NAME", "auth_token" )
  end

  def authorizations_in_cookie?
    given_token = cookies[ cookie_name ]
    return false if given_token.blank?

    decode( given_token ).present?
  end

  def authorize_by_cookie( expected_role )
    given_token = cookies[ cookie_name ]
    return unauthorized if given_token.blank?
    return nil if token_has_role? given_token, expected_role

    unauthorized
  end

  def authorizations_in_header?
    given_token = request.headers[ "Authorization" ]
    return false if given_token.blank?

    pieces = given_token.split
    return false if pieces.size != 2 || pieces.first != "Bearer"

    decode( pieces.second ).present?
  end

  def authorize_by_header( expected_role )
    given_token = request.headers[ "Authorization" ]
    return unauthorized if given_token.blank?

    pieces = given_token.split
    return unauthorized if pieces.size != 2 || pieces.first != "Bearer"
    return nil if token_has_role? pieces.second, expected_role

    unauthorized
  end

  private

  def token_has_role?( given_token, expected_role )
    payload = decode( given_token )

    payload[ "roles" ].include? expected_role
  rescue JWT::DecodeError
    false
  end

  def decode( given_token )
    body = JWT.decode(
      given_token,
      public_key,
      true,
      { algorithm: Token::SIGNING_ALG, verify_expiration: true }
    )
    return nil if body&.size&.zero?

    body.first
  end

  def public_key
    OpenSSL::PKey::RSA.new ENV[ "JWT_RSA_PUB" ]
  end
end

app/controllers/patrons_controller.rb
# frozen_string_literal: true

class PatronsController < ApplicationController
  before_action -> { authorize_by_cookie "manage_patrons" }
  before_action :load_resource

  def show; end

  def add_role
    @resource.add_role params[ :new_roll ]
    redirect_to patron_path( @resource )
  end

  private

  def load_resource
    param = params[ :name ].presence || params[ :patron_name ]
    @resource = Patron.find_by external_id: param
    return nil if @resource.present?

    redirect_to roles_path
  end
end

app/controllers/roles_controller.rb
# frozen_string_literal: true

class RolesController < ApplicationController
  before_action -> { authorize_by_cookie "manage_roles" }
  before_action :load_resource, only: [ :edit, :update ]

  def index
    @roles = Role.all.limit( 50 ).includes :patrons_roles
  end

  def edit
    @patrons = @resource.patrons.limit 50
  end

  def update
    @resource.update resource_params
    redirect_to roles_path
  end

  private

  def load_resource
    @resource = Role.find_by name: params[ :name ]
    return nil if @resource.present?

    redirect_to roles_path
  end

  def resource_params
    params.require( :role ).permit( :name )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% title = [ content_for( :title ), "Maitre D" ].compact.join(" | ") %>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" media="all" href="/pico/pico-v1.3.3.min-dist.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <main class="container"><%= yield %></main>
    <footer>
      <div class="container">
        <%= link_to "Logout", logout_path %>
      </div>
    </footer>
  </body>
</html>

app/views/patrons/show.html.erb
<% provide :title, "Patron" %>

<h1><%= content_for :title %></h1>

<p>
  <%= @resource.external_id %> - <small><%= @resource.auth_type.humanize %></small>
</p>

<h3>Roles</h3>

<table roll="grid">
  <thead>
    <tr>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    <% @resource.roles.each do | role | %>
      <tr scope="row">
        <td><%= role.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<%= form_with action: :post, url: patron_add_role_path( patron_name: @resource.external_id ) do | f | %>
  <div>
    <%= f.label :new_roll %>
    <%= f.text_field :new_roll %>
    <br />
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<% provide :title, "Edit Role" %>

<hgroup>
  <h1><%= content_for :title %></h1>
  <%= link_to "↩ Index", roles_path, class: "secondary" %>
</hgroup>

<%= form_for @resource, url: role_path( name: @resource.name ) do | f | %>
  <div>
    <%= f.hidden_field :old_name, value: @resource.name %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />
    <%= f.submit %>
  </div>
<% end %>

<hr />

<br />
<hgroup>
  <h2>Patrons</h2>
  <small>Patrons that have this role (<%= @resource.patrons.count %> total)</small>
</hgroup>

<table role="grid">
  <tbody>
    <% @resource.patrons.each do | patron | %>
      <tr>
        <td><%= patron.external_id %></td>
        <td><%= patron.auth_type.humanize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/roles/index.html.erb
<% provide :title, "Roles" %>

<hgroup>
  <h1><%= content_for :title %></h1>
  <small>All roles in the system</small>
</hgroup>

<table role="grid">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Patrons</th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do | role | %>
      <tr scope="row">
        <td><%= link_to role.name, edit_role_path( name: role.name ) %></td>
        <td><%= role.patrons.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_error_msg.html.erb
<% @error_status = {} %>
<% if flash[ :error ].present? %>
  <div class="error-msg">
    <%= flash[ :error ] %>
  </div>
  <% @error_status[ "aria-invalid" ] = true %>
<% end %>